[package]
name = "tile-split"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "^4", features = ["env", "derive"], optional = true }
image = "^0.24.7"
zorder = "0.1.0"

[features]
cli = ["clap"]

[[bin]]
name = "tile-split"
required-features = ["cli"]
