[package]
name = "tile-split"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast_image_resize = "^2.7.3"
oxipng = { version="^9.0", default-features=false }

[profile.release]
lto = true
